### ISSUE TITLE
Identifying incompatible mods

### ISSUE THREAD

**Issue by BrekiTomasson** [Draylar/tiered#26]
So I'm trying to narrow down which of my many mods are failing to add their items to the correct `fabric` tags, but still seem to be missing some. Any way you could imagine making the crash log more informative so that we poor mod pack developers can have an easier time identifying which mods need fixing? The classic `java.lang.NoSuchFieldException: MAINHAND` doesn't give me much to work with other than it's most likely a tool rather than armor. :)

**Comment by Draylar** [comment]
Could you [provide your full game log](https://minecrafthopper.net/help/guides/getting-minecraft-launcher-log/)? Tool tags should not be causing a crash like that.

**Comment by itschonky** [comment]
i encountered the same problem (i think) while generating a world, not sure if its only specifically when you create a world though
my game output crash log = https://pastebin.com/K6kt6ug5
not really able to post the launcher log since its huge and none of the sites i know support more than 1mb, sorry about that
anyways i hope this helps in some way

**Comment by BrekiTomasson** [comment]
@Draylar Here you go: https://paste.ubuntu.com/p/mBvkxYcVr4/

I've tried disabling a number of different mods, but no matter how I try it still throws the same error, so I'm beginning to suspect it's not just item tags.
