### ISSUE TITLE
Console spam after Tiered is remove

### ISSUE THREAD

**Issue by DanShu15** [Draylar/tiered#6]
I saw that this was having issues on a dedicated server after realizing it wasn't adding attributes to our stuff so I took it out with this last round of updates.
Is it possible that removing this could cause console spam after removal?

12.06 20:15:06 [Server] Server thread/WARN Ignoring unknown attribute 'generic.reach-entity-attributes.reach'
12.06 20:15:06 [Server] Server thread/WARN Ignoring unknown attribute 'generic.reach-entity-attributes.attackRange'

Logs
https://pastebin.com/vZQTus19
https://pastebin.com/hiTku5h7

I'll try putting it back in next update, or if I notice the server is empty :)

**Comment by Draylar** [comment]
This seems to be an issue that stems from vanilla (out of my control unless I provided a separate mod to fix it). 

There's a tag saved to LivingEntities with an `Attributes` property that stores the entity's current attributes. When it's read, it tries to grab the component from the entity's component container. If the attribute doesn't exist, the game prints an error. You can see my 2 custom attributes (digSpeed and critChance) in the log; they aren't spamming because mine *only* attach to players, while the reach attributes (which comes from [Reach Entity Attributes](https://github.com/JamiesWhiteShirt/reach-entity-attributes)) applies to all entities.

If you wanted, I could send you a patch mod that nukes entity attributes that don't exist. It would be a one-time use-and-done thing, as long as you loaded all the entities with the invalid attributes. The other option would be adding Tiered 1.1.0 beta, which should work on servers.

**Comment by DanShu15** [comment]
Sorry, I went to sleep before the server reset or I'd have reported that adding it back in works just fine for clearing up the log spam as well as another error reported here https://github.com/CottonMC/Cotton/issues/44
I'm not very good at reading the logs unfortunately, but all I had done is removed tiered1.1.0 beta and made some recipe datapacks. I'd never seen removing a mod do that before so I assumed it was my datapacks and Cotton. I checked the data packs right away and posted the next version of the modpack with tiered included and another jar waiting to be reactivated next server restart.

No patch is necessary, the mod was linked as a suggested mod for our server and I'd had a similar mod when I briefly tried the RAD modpack for 1.12 - so the problem the whole time was me not properly adding items to tags and setting it up. I had assumed it was preconfigured and didn't do my due diligence. When I noticed our equipment didn't have tiers (since I'd dik'd the setup) and what must be older posts saying it wouldn't work on a dedicated server while checking for an update - I took it all to mean that our 1.1.0b wasn't dedicated server compatible at the moment.

Totally user error, and I'm really sorry to have wasted your time like this. I certainly appreciate the full explanation and would like to see what a patch like that looks like someday, but we'll be keeping the mod installed and actually setting it up properly LOL.

Thank you again, and again I do apologize
